# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Re-Build Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/rep-porto/web
            sudo docker build --no-cache -t rp .

      - name: Restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop rp
            sudo docker rm rp
            sudo docker run -d -p 8110:8110 -v portfolio-data:/app/data --name rp rp
